# Site settings
title: Kunsun
description: "A minimal blog, build with Jekyll."
url: "http://www.kunsun.info"
author:
  name: "kunsun"
  email: "yangkunid91@gmail.com"
  url: "http://www.kunsun.info"
  github: "kunsun"

baseurl:  /
comments: true
markdown: rdiscount
highlighter: pygments
permalink: pretty
paginate: 8
paginate_path: /page:num/

# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"

version: "1.0.1"

custom_header: false
custom_nav_footer: false
reverse: false
